### ISSUE TITLE
截图，上传文件失败（非复制图片文件）报错为UnCaught TypeError:  img.toPng is not a function 

### ISSUE THREAD

**Issue by DRPrincess** [knightli/markdown-assistant#18]
之前正常使用，这周使用出现以下问题：

![wechatimg112](https://user-images.githubusercontent.com/16207639/43061559-5483faae-8e88-11e8-9e4d-4630a2d894de.jpeg)

因为上传的加载框出错，无法关闭，出错信息只能看个大概，截图如上。

请问这个问题怎么解决？

**Comment by luoei** [comment]
和你一样的错误，
<img width="1191" alt="wx20180723-155841 2x" src="https://user-images.githubusercontent.com/3114511/43064378-560a6080-8e91-11e8-845b-f7437e9302d6.png">

**Comment by DRPrincess** [comment]
@xispower  我至今未解决，你找到方法了吗？

**Comment by tychenjiajun** [comment]
@xispower @DRPrincess 应该是electron的函数名有变动，见[nativeImage](https://electronjs.org/docs/api/native-image#native-imagesettemplateimage)  
修改main.coffee第57行代码即可，欢迎pull request

**Comment by luoei** [comment]
@DRPrincess 目前还没有时间来研究atom插件写法，当然也就没有解决这个问题。不过我中转了一下，我写了一个sh脚本，加入环境变量，每次执行upload-qiniu.sh image_path 后，再把打印出的路径放在这里。

**Comment by wangbo5759** [comment]
@xispower @DRPrincess 
/Users/wangbo5759/.atom/packages/markdown-assistant/lib/main.coffee  把本地main.coffee文件中57行的img.toPng()改成img.toPNG()就行了

**Comment by morethink** [comment]
OK了@wangbo5759
