### ISSUE TITLE
Uncaught TypeError: img.toPng is not a function

### ISSUE THREAD

**Issue by fenglh** [knightli/markdown-assistant#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.2
**Thrown From**: [markdown-assistant](https://github.com/knightli/markdown-assistant) package 0.2.0

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At /Users/fenglihai/.atom/packages/markdown-assistant/lib/main.coffee:57

TypeError: img.toPng is not a function
    at uploadFn (/packages/markdown-assistant/lib/main.coffee:57:34)
    at /packages/markdown-assistant/lib/insert-image-view.coffee:63:9
```

### Commands

```
     -0:11.9.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
markdown-assistant 0.2.0 
qiniu-uploader 0.0.5 
```

**Comment by fenglh** [comment]
靠，自行解决了！
1. 修改`/Users/fenglihai/.atom/packages/markdown-assistant/lib/main.coffee`文件的第57行，把toPng改成toPNG
2.`cd /Users/fenglihai/.atom/packages/markdown-assistant && npm install`

**Comment by intellijboy** [comment]
thank you!
