### ISSUE TITLE
Ubuntu 14.04.1 LTS下没反应

### ISSUE THREAD

**Issue by fsxchen** [knightli/markdown-assistant#7]
Ubuntu 14.04.1 LTS下没反应,
atom版本1.5.3

**Comment by Anderson-Liu** [comment]
我用的是Mint Linux,通过检查源代码，发现是没有监听"Ctrl + V "组合键，已向作者提交pull request.
可以考虑先自己在markdown-assistant/lib/main.coffee内添加对于"Ctrl + V"的监听。

**Comment by DinoStray** [comment]
这个问题我也遇到了, 貌似不止ubuntu, windows也一样, 是不是都没设置"Ctrl + V"的监听

**Comment by FrankFang** [comment]
是的

**Comment by FrankFang** [comment]
发布了 0.2.0，有人试试吗？  @DinoStray   @lhongda @fsxchen
